"""Initial migration.

Revision ID: 4abfafaf3d92
Revises: 
Create Date: 2021-06-23 00:24:09.117962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abfafaf3d92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('work_orders', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('work_orders', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_index('service_id', table_name='work_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('service_id', 'work_orders', ['service_id'], unique=False)
    op.drop_column('work_orders', 'end_time')
    op.drop_column('work_orders', 'start_time')
    op.drop_column('work_orders', 'name')
    # ### end Alembic commands ###
