"""Adding Created At to Work Orders.

Revision ID: bda189d9227c
Revises: 4abfafaf3d92
Create Date: 2021-06-23 00:51:09.847327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda189d9227c'
down_revision = '4abfafaf3d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'created_at')
    # ### end Alembic commands ###
